### ISSUE TITLE
多多岛

### ISSUE THREAD

**Issue by yuejuanmyword** [doocs/coding-interview#4]
```js
success: function (res) {
							 res = res || {};
							 //console.log(res.meta.success);
							 var success = res.meta.success || ''
							 if(success === true){
								 tomcat('提交成功');
							 }else{
								 tomcat('提交失败');
							 }
```

**Comment by yuejuanmyword** [comment]
> ```js
> success: function (res) {
> 							 res = res || {};
> 							 //console.log(res.meta.success);
> 							 var success = res.meta.success || ''
> 							 if(success === true){
> 								 tomcat('提交成功');
> 							 }else{
> 								 tomcat('提交失败');
> 							 }
> ```

**Comment by yanglbme** [comment]
@yuejuanmyword 同学，你这是干嘛...
